version: "3.7"

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    volumes:
      - ./data:/data
      - ./import:/import
      - ./plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=none