### Register request
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
   "username": "octav",
   "password": "test"
}


### Login request
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username": "octav",
   "password": "test"
}
