### Get all stories
GET http://localhost:3000/api/read/story
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3


### Get story
GET http://localhost:3000/api/read/story/7
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3


### Get all scenes for a story
GET http://localhost:3000/api/read/story/7/scene
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3


### Get scene of a story
GET http://localhost:3000/api/read/story/7/scene/12
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3


### Get all choices for a story
GET http://localhost:3000/api/read/story/7/choice
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3


### Get choice of a story
GET http://localhost:3000/api/read/story/7/choice/13
Content-Type: application/json
Authorization: 42792a3f-6bd0-4810-bf4b-50126419cfc3
